// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace stmgr {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class TupleMessage;

// ===================================================================

class TupleMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.stmgr.TupleMessage) */ {
 public:
  TupleMessage();
  virtual ~TupleMessage();

  TupleMessage(const TupleMessage& from);

  inline TupleMessage& operator=(const TupleMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TupleMessage& default_instance();

  void Swap(TupleMessage* other);

  // implements Message ----------------------------------------------

  inline TupleMessage* New() const { return New(NULL); }

  TupleMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TupleMessage& from);
  void MergeFrom(const TupleMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TupleMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 id = 2;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // optional string data = 3;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const char* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // required double time = 4;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 4;
  double time() const;
  void set_time(double value);

  // @@protoc_insertion_point(class_scope:proto.stmgr.TupleMessage)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_time();
  inline void clear_has_time();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  double time_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static TupleMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TupleMessage

// required string name = 1;
inline bool TupleMessage::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TupleMessage::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TupleMessage::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TupleMessage::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& TupleMessage::name() const {
  // @@protoc_insertion_point(field_get:proto.stmgr.TupleMessage.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TupleMessage::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.stmgr.TupleMessage.name)
}
inline void TupleMessage::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.stmgr.TupleMessage.name)
}
inline void TupleMessage::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.stmgr.TupleMessage.name)
}
inline ::std::string* TupleMessage::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:proto.stmgr.TupleMessage.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TupleMessage::release_name() {
  // @@protoc_insertion_point(field_release:proto.stmgr.TupleMessage.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TupleMessage::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:proto.stmgr.TupleMessage.name)
}

// required int32 id = 2;
inline bool TupleMessage::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TupleMessage::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TupleMessage::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TupleMessage::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 TupleMessage::id() const {
  // @@protoc_insertion_point(field_get:proto.stmgr.TupleMessage.id)
  return id_;
}
inline void TupleMessage::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:proto.stmgr.TupleMessage.id)
}

// optional string data = 3;
inline bool TupleMessage::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TupleMessage::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TupleMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TupleMessage::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& TupleMessage::data() const {
  // @@protoc_insertion_point(field_get:proto.stmgr.TupleMessage.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TupleMessage::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.stmgr.TupleMessage.data)
}
inline void TupleMessage::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.stmgr.TupleMessage.data)
}
inline void TupleMessage::set_data(const char* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.stmgr.TupleMessage.data)
}
inline ::std::string* TupleMessage::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:proto.stmgr.TupleMessage.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TupleMessage::release_data() {
  // @@protoc_insertion_point(field_release:proto.stmgr.TupleMessage.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TupleMessage::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:proto.stmgr.TupleMessage.data)
}

// required double time = 4;
inline bool TupleMessage::has_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TupleMessage::set_has_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TupleMessage::clear_has_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TupleMessage::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline double TupleMessage::time() const {
  // @@protoc_insertion_point(field_get:proto.stmgr.TupleMessage.time)
  return time_;
}
inline void TupleMessage::set_time(double value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:proto.stmgr.TupleMessage.time)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace stmgr
}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
